---
ID: "6105620e-951f-42d4-a342-3072ba808c17"
Parent: "3260c793-9a85-4d27-a0c9-e90edf1f656d"
Template: "3260c793-9a85-4d27-a0c9-e90edf1f656d"
Path: /sitecore/templates/Project/Adnoc/Components/adnocgas/VideoSection/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260328T140446Z
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2307bb4d-1f1c-4055-b547-2fca7890f117"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260328T140446Z
