---
ID: "2a92c846-3d18-4210-9d76-91b42a371549"
Parent: "cf5cbea0-f6ef-463c-9673-e35fd200d451"
Template: "cf5cbea0-f6ef-463c-9673-e35fd200d451"
Path: /sitecore/templates/Project/Adnoc/Components/adnocgas/Footer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260328T140436Z
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6d9cb86b-ad58-4ea5-8a71-df5df9dc13f7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260328T140436Z
