---
ID: "83b63031-af0e-480b-ab46-e09aaff48b54"
Parent: "dd4b1514-9e9d-44c8-88d9-ea61acda2152"
Template: "dd4b1514-9e9d-44c8-88d9-ea61acda2152"
Path: /sitecore/templates/Project/Adnoc/Components/HeroVideo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260328T134524Z
